### ISSUE TITLE
VS Code Recommendations

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#128]
Previously we noticed that if you opened a .soar file in VS Code, it would tell you that the Soar Language Plugin existed and could help with that file.

I also noticed that VSCode is recommending various extensions to me in the extensions panel, and when I hover over them it tells me why it's recommending it. E.g., it's recommending "Notepad++ keymap" because I have Notepad++ installed. I wonder if we could do something to cause Soar Language Plugin to get recommended (e.g., check for Soar on the path or something?). I'm not sure what exactly it can check to make recommendations, but it could be worth looking into.

**Comment by adeschamps** [comment]
I'm having a hard time finding any documentation about how an extension developer might influence this.

**Comment by adeschamps** [comment]
I'm going to close this for these reasons:
- I can't find any documentation about how we as extension developers influnce this.
- It's unclear what it means for Soar to be "installed". JSoar is typically added as a project dependency, and not globally available on a system.
- Personally, I think that extensions should be recommended at the moment the user would find them useful, not when the open their editor to work on something unrelated.
