### ISSUE TITLE
Move cursor to top of file when showing new expansion

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#141]
Reproduction steps:

1. Click on some tcl code that expands
2. Place cursor in ~tcl-expansion.soar somewhere far down
3. Click on some other tcl code that expands into an amount that is shorter than the current cursor position in the ~tcl-expansion.soar file

What appears to happen is that the cursor is repositioned to the last line of ~tcl-expansion.soar, which is usually (always?) blank, and the file is scrolled so that that line is at the very top of the window. This effectively makes ~tcl-expansion.soar look blank (if you manually scroll up, everything is fine).

In this situation, I'd like the cursor to automatically return to the top of the file. This avoids the confusion where it looks like things aren't working.

I'm marking this as both an enhancement and a bug, because while it's not a really a bug, it's sufficiently confusing that people will think it's a bug, so I think it's fairly urgent.

**Comment by adeschamps** [comment]
Fixed in #142
