### ISSUE TITLE
Valid source command marked as error

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#178]
The following command, which is valid in jsoar out-of-the-box, gets marked as an error:
```
source classpath:/tcl/pkg/tcllib/library/struct/record.tcl
```
The error is `File not found`. Support for `classpath:` is something jsoar provides; it doesn't come with tcl natively. Are we potentially by-passing jsoar here and using tcl directly?

Windows 10, VS Code plugin 0.9.12

**Comment by marinier** [comment]
Another thing I tried was using Soar's `warning --off` before the command, and `warning --on` after. But this doesn't work, probably because it's not really a warning, but possibly also because somehow Soar LSP is bypassing Soar somehow at this point.

**Comment by marinier** [comment]
This is actually preventing me from using a Tcl library, because it fails to load in LSP (even though it loads fine in jsoar), and because of that any use of that library in the code is also reported as an error, which makes it basically impossible to develop efficiently, because I can't know what errors I really have until runtime.

**Comment by marinier** [comment]
I was able to come up with a workaround (basically, get the file I want, add it to my agent, and source it as a normal file). This isn't great, but it'll work for now.

**Comment by adeschamps** [comment]
First, a side note, this is a case where the behaviour of JSoar and CSoar differ. I don't think I'd bother for just this case, but if there are other examples of implementation-specific behaviour, I'd consider adding a field to the `soarAgents.json` manifest to optionally specify the target implementation.

---

It shouldn't be too hard to implement sourcing from the classpath. The server loads files from the filesystem in the `readFile` static method of the `SoarFile` class; I assume we could just borrow a function or two from JSoar, and add a new branch to that `readFile` method.

The bigger issue in my mind is how to populate the classpath in the first place.  I can think of a few options that all have tradeoffs. Please let me know if I'm missing something.
- Should we expect the developer to set their `CLASSPATH` environment variable before they launch the server? That feels very inconvenient, especially when you consider that it would probably require the user to restart their editer.
- Should we have the developer set their classpath in `soarAgents.json`? This might be the simplest. But we intend for `soarAgents.json` to be added to source control, and classpaths are probably specific to the particular developer's environment.
- Can we look at a `pom.xml` or `build.gradle` file and determine the classpath from that? This seems like it would add a great deal of complexity.

---

Would it be useful to support sourcing from the classpath _without_ dealing with how the classpath gets populated? If so, then I can probably add that feature. If, however, populating the classpath is necessary - and if there's no simpler approach than the ones I've listed above - then I don't think I have time to get this implemented in the near future. If someone is interested in taking this on, I'd be happy to walk them through the codebase and accept a pull request.

**Comment by marinier** [comment]
For now, I think it would be fine to source from the classpath without assuming it is populated beyond what you're already doing. For the specific example I gave, that is already built into jsoar, which is presumably already on the classpath.

In the future, it would be nice to be able to deploy soar code on nexus and include it via classpath. In fact, the only reason I don't do this now is because the Soar IDE (old, and now new) don't support it. Looking at the maven/gradle files would be ideal, since that would most accurately reflect the runtime environment, but I think specifying it in `soarAgents.json` would actually be ok. In most cases, it would just have to be relative to the `.m2` directory. The `.m2` directory location is probably discoverable on each platform.

If we thought that having user-specific settings was desirable, we could introduce a new file (e.g., `soarUser.json`) that isn't intended to be checked in (similar to Visual Studio's user file).

As far as other jsoar/csoar specific stuff goes, there's definitely more differences. I actually have `if` statements in my tcl to control what gets loaded depending on whether it's running on jsoar or csoar. The main thing is that there are different commands available. JSoar also supports inline scripting languages (javascript, python, etc.). The RHS functions also differ. So if the LSP knew which one it was supposed to be emulating, it could give the appropriate error messages (e.g., if a jsoar function was used in csoar mode). This could also provide a way to make the IDE features work on the csoar-specific code (normally that code doesn't get executed in the LSP because it's running on jsoar). Of course, what that code is doing may not be executable on jsoar, but errors about missing commands, etc., can be suppressed if they are known to be legal on the target platform.

**Comment by adeschamps** [comment]
Can you help me understand this? It seems from the source of JSoar that it has special handling for the `jar` scheme:
https://github.com/soartech/jsoar/blob/868b47ab16262d8f4074c641ad3a5a22c89277eb/jsoar-core/src/main/java/org/jsoar/util/UrlTools.java#L41.

How does JSoar handle the `classpath` scheme?

**Comment by marinier** [comment]
Yes, jsoar does have special handling for jar URLs. It also has special handling for the `classpath:` prefix:

https://github.com/soartech/jsoar/blob/868b47ab16262d8f4074c641ad3a5a22c89277eb/jsoar-core/src/main/java/org/jsoar/kernel/commands/SourceCommand.java#L171
and
https://github.com/soartech/jsoar/blob/868b47ab16262d8f4074c641ad3a5a22c89277eb/jsoar-core/src/main/java/org/jsoar/util/UrlTools.java#L120

But for some reason, the `source` line at the top of this issue is still marked as an error. Maybe it actually works when run through jsoar, but the Soar LSP's top-level parser is failing on it and spuriously marking it as an error? I assume jsoar and jtcl are on the classpath, but is it possible that somehow they're not?

**Comment by marinier** [comment]
What's strange is that if I execute this line from the jsoar debugger directly, it works fine. But it doesn't work inside the LSP.

BTW, this is sourcing something that is contained inside of jtcl, so you can try it yourself without any additional source code. It sources no rules -- it just sources tcl procs and variables (as it's part of the tcl standard library).

**Comment by adeschamps** [comment]
The language server never invokes JSoar's `source` command; it opens and parses the file, and evaluates each statement individually. The file IO happens in the server and has nothing to do with how JSoar opens files.

We generally don't want to allow JSoar to source files, because that would change the state of the interpreter. Procedures, variables, and productions would be defined, but we wouldn't get to see where. Perhaps we should still implement this as a fallback though.

**Comment by adeschamps** [comment]
Also, JSoar and jtcl are on the classpath, because they're dependencies of the server.

**Comment by marinier** [comment]
Ok. Then it seems the ideal solution would be to implement support for `classpath:` in LSP, so those things could be tracked. But using jsoar directly as a fallback seems very reasonable (and is presumably less work) -- there will undoubtedly be additional edge cases we haven't run into yet.

FWIW, what jsoar is doing internally is using spring-core to get things off the classpath. So the LSP could presumably do the same thing (you can rip the thin wrapper right out of jsoar).

**Comment by adeschamps** [comment]
Agreed. Falling back to JSoar's source implementation should eliminate errors from undefined functions and so on, but you wouldn't get doc strings on hover, and go-to-definition would only be able to go to where the `source` command was called.

For cases where we _do_ analyse the file from the classpath, one possible edge case I'm concerned about is that some editors might not be able to open files when you try to go-to-definition.

**Comment by marinier** [comment]
I'm not too concerned about some features not working in some cases in some editors. As long as it degrades gracefully (i.e., doesn't crash or cause errors), then it just won't work in those cases, and that's already true for lots of things in other editors (e.g., last I looked, sublime's LSP support was pretty limited).

If you wanted to be fancy, you could show something (in the status bar? As a tooltip?) to say that whatever it is isn't found, but that's not strictly necessary. (We could add something to the README along the lines of "Why doesn't feature X work?" and then give possible reasons, including this.
