### ISSUE TITLE
Add code formatter

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#34]
The old Eclipse Soar IDE had a code formatter that could be applied to selected lines or an entire file. While useful on it's own, the real value is in applying it to the code expansion buffer. Code generated by tcl procs can be very messy in term of indentations. Auto formatting it can make it much more readable.

Not sure, but maybe the formatting code from Eclipse can be ported. Or probably it's super simple (e.g., indent conditions/actions by a fixed amount, and negated blocks get indented again).

**Comment by adeschamps** [comment]
I like this idea (I like code formatters in general). If it's really simple, then it makes sense to build it right in. If it's something more complex, then I'd consider extracting it as a more general-purpose tool (although maybe not initially, since then it becomes its own project).

**Comment by marinier** [comment]
I'm using VSCode to write some new test Soar code from scratch, and it's pretty painful without automatic formatting as I type (everything has to be manually indented). I think we'll want to do something here (even if it's really simple) for the 1.0 release.

**Comment by adeschamps** [comment]
I was about to say "this might be the job of individual editors", but then I discovered [`textDocument/onTypeFormatting`](https://github.com/Microsoft/vscode/issues/44953). This is different from `textDocument/formatting` and `textDocument/rangeFormatting`, which would normally be invoked manually by the user (or maybe on save, if you're the sort of person who configures their editor that way).

With `onTypeFormatting`, the server says "these are my trigger characters" (usually delimiters or newlines) and the client will request `TextEdit`s any time those characters get typed.

**Comment by adeschamps** [comment]
Having had some insight into formatters for various other languages, I believe this is a much larger task than it might seem on the surface. Additionally, I think that code formatters should be useable as standalone tools. I would recommend this as a separate project for anyone interested.

If someone does undertake this, a formatter should consist of:
- A library with an API that would be useable by the language server.
- A CLI wrapper around this library that can be run from the command line or easily invoked by tools

I'd very much like to talk to anyone who's interested in taking this on, but for now I'm going to close this issue.
