### ISSUE TITLE
Handle csoar commands/options/RHS functions

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#37]
Because not every command, command option, and RHS function has been ported from csoar to jsoar, some csoar projects will get spurious errors about these being undefined. We should provide a means of preventing these. Possibilities include:

* A list of known csoar commands, options, and RHS functions. When an error comes up for something on the list, the error is suppressed. Ideally configurable, so new items can be added as csoar changes over time.
* Dummy commands/RHS functions for missing functionality. They don't do anything, but they suppress the errors. They probably don't check the arguments, as those can be very complex. I believe the old Soar IDE did some of this.
* Ability to suppress specific warnings/errors (e.g., via a specially formatted comment).
* Run csoar inside instead of jsoar (presumably the project would have to specify which one it wanted to use). This is presumably hard.

**Comment by adeschamps** [comment]
I borrowed the list of ignored commands from the SoarIDE. I think that's enough for an initial beta. The list isn't configurable right now, but that would be pretty easy to do if anybody needs it.

**Comment by marinier** [comment]
I agree this is good enough for the beta, but that list is probably not very accurate, since the old SoarIDE hasn't been updated since csoar significantly changed their command structure (which we largely ported to jsoar as well). But we can adjust the list for the final release if needed.
