### ISSUE TITLE
No error generated for bad top-level command or variable

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#49]
Bad top-level commands, and bad variable arguments to top-level commands, do not generate errors.

In these examples, the file/project only contains the text shown.

```foo bar```
`foo` is not a valid top-level command, so this should be an error.

or

```print $foo```
`print` is a valid command, but `$foo` is not defined, so this should be an error.

Neither of these generate errors.

**Comment by marinier** [comment]
Here's another example that should generate an error but doesn't -- technically not a top-level command, but I suspect related:

```
if { 1 } {
    print $foo
}
```

**Comment by adeschamps** [comment]
I fixed this, but I want to keep the issue open for a bit in case there were unintended side effects. The change I made will result in more errors being reported, which I'm hoping does not include any false positives.

**Comment by adeschamps** [comment]
This has been fixed for a while and I haven't heard of any bugs that were introduced by it.
