### ISSUE TITLE
Putting the cursor in the ~tcl-expansions.soar file clears the file

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#50]
In VS Code (other editors not tested)

1) Open some agent file that has something that will expand
2) Open the ~tcl-expansions.soar file and arrange so files are side-by-side
3) Click on something in the agent file that puts some expanded code in ~tcl-expansions.soar
4) Click in the ~tcl-expansions.soar file (e.g., as if you were going to copy something from there)

The ~tcl-expansions.soar file clears, but it should not.

**Comment by marinier** [comment]
Workaround: save the ~tcl-expansions.soar file and open in another editor.

**Comment by adeschamps** [comment]
The workaround shouldn't be necessary; this is a pretty simple fix. There are a number of cases where making a query for a file that isn't part of the agent results in an error of some sort. In many cases it's harmless (an exception gets thrown and caught) but this one has side effects.
