### ISSUE TITLE
Re-analysis doesn't always occur when editing a file

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#53]
It seems that in many cases if I edit a file and save it, the analysis doesn't update. (This is in VSCode.) Watching the console output, I can see some LSP messages get generated, but the agent clearly isn't being re-loaded. It doesn't matter how long I wait. I often have to close/reopen the workspace to get an updated analysis.

For example, to test #49, I took an existing agent that used a valid tcl variable and changed it to an invalid variable and saved. No new errors were generated. When I closed and reopened the workspace, the new error appeared.

**Comment by adeschamps** [comment]
I've been experiencing similar things, although I haven't yet pinned down a cause.

**Comment by adeschamps** [comment]
Are you still experiencing this issue? I've encountered it before, but I can't reproduce it right now, even though I don't specifically remember fixing it.

**Comment by marinier** [comment]
I believe this was fixed in b260300ee27ac820f9e6928360299d3f20eed047.

I would say the only thing I don't think causes an update that probably should is editing the `soarAgent.json` file.

**Comment by marinier** [comment]
I'm closing this issue since there is already a separate issue for updating when editing `soarAgents.json` (#63 ).
