### ISSUE TITLE
Depend on public release of JSoar

### ISSUE THREAD

**Issue by adeschamps** [soartech/soar-language-server#58]
We currently depend on JSoar via a git submodule pointing to a branch. JSoar is moving towards being deployed to Maven Central, with our changes on that branch being included. Once that's done, we can eliminate the submodule and change JSoar to a normal dependency.

**Comment by adeschamps** [comment]
@marinier Do you know if any progress has been made on this?

**Comment by marinier** [comment]
@rdfred has done some significant work on resolving remaining issues with jsoar, but it's still not ready for release. I believe there is some kind of deadlock with the debugger. But that shouldn't affect this project, so if we wanted to we could do a public release of the snapshot version and you could depend on that. But I'm not sure exactly how we want to deploy it (e.g., whose keys do we want to use).

**Comment by adeschamps** [comment]
If you're releasing manually (which I'd recommend, given the slow cadence of JSoar releases), then you should use the personal credentials of whoever's doing the release.

If you wanted to deploy from CI (which probably isn't worth the trouble of setting up) then you'd probably want to create credentials for the CI machine, and then configure your repo to limit who gets to commit to the deployment branch.

**Comment by marinier** [comment]
An update on this: jsoar is ready for release (of course there's always more to do, but it's good enough right now). @sirnuke reports that he is working on getting all the accounts set up for Soar LSP (now that we have @soartech-releases), and that getting jsoar publicly released should be trivial once he's worked through that.

FWIW, I believe all the latest jsoar stuff has been pushed to github. There has been a minor API change (the methods used to get errors had the word `Tcl` in their names for no good reason, so those have been renamed).

**Comment by adeschamps** [comment]
I had the honour of closing this in #226 .
