### ISSUE TITLE
Update vscode extension info

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#61]
In vscode, the extension page shows a bunch of info across multiple tabs. Some of this info may be outdated, and some is entirely missing (e.g., the changelog). We should update this for the final release.

**Comment by adeschamps** [comment]
We also should make sure we mention the `soarAgents.json` file in here, since people installing via the marketplace won't be looking at the main readme on GitHub.

**Comment by adeschamps** [comment]
I revised the VSCode extension README to be more user-oriented, and copied some of the `soarAgents.json` explanation from the root README.
