### ISSUE TITLE
Don't print stack traces for "ok" exceptions

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#65]
When a hover is attempted in a file that isn't part of the agent, internally an exception is thrown because the analysis for the file isn't found. This is caught and printed. The issue is that in the console output an exception trace is shown, which makes it look like there's an actual issue, when in fact this is "by design".

The best solution would be to avoid using exceptions for control flow at all -- e.g., check to see if the analysis was found before trying to use it. But if that is onerous, then at least in this case we should not print the stack trace (although I suspect that is actually harder, since the place that prints may not be able to distinguish between "ok" exceptions and real errors, and we don't want to suppress real errors).

**Comment by marinier** [comment]
In briefly looking at the code in `ProjectAnalysis.java`, I like the pattern established by `file()`, which returns an `Optional`. I think all the other analyses (variables, procedure definitions, and procedure calls) should have similar getters, and the actual members should be made private. Then it will be explicit that these calls could "fail". The callers can then check the results before trying to use them, and bail out early if there is no result. This would avoid exceptions entirely in these cases.

I'm not sure if there are other cases beyond these. I'll need to discuss with Anthony.

**Comment by adeschamps** [comment]
Fixed in 16e0b00
