### ISSUE TITLE
Emit error if soarAgents.json file isn't found

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#66]
In order to help users discover that they need a `soarAgents.json` file, we should emit a warning when it isn't found. The warning should indicate the expected location of the file, and potentially link to documentation explaining how to create it.

I believe Bryan asked for this.

**Comment by marinier** [comment]
I actually wonder if this should be an error. Currently there is a fallback behavior of using whatever file is opened as the "root" file, but this isn't a terribly useful fallback -- it will likely result in tons of spurious errors and missed analyses. It might be better to require `soarAgents.json`, and if it is missing emit an error and perform no analyses (which has the added benefit of ensuring that this is the first problem and thus is easy to see).

**Comment by adeschamps** [comment]
Good idea, I prefer the route of making it an error.

**Comment by adeschamps** [comment]
This is fixed now.

In VSCode, if you click on the error message then it will try to open the file but fail. This isn't perfect, but I think it's good enough for a 1.0 release, so I'm going to close this and create a new issue.
