### ISSUE TITLE
Add outline view

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#72]
I don't know if LSP supports this, but the feature I miss most from the old Soar IDE at this point is an outline view. This basically lists (and links to) all the top-level commands in the current file. It's sortable into file order or alphabetical.

If LSP doesn't support this directly, I could imagine emulating by generating a temporary file that updates with this information (like tcl expansion), with links on the entries to the relevant parts of the current file.

**Comment by adeschamps** [comment]
I believe this is supported by the [`textDocument/documentSymbol`](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol) request.
