### ISSUE TITLE
Consider using code lens to display tcl variable values

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#74]
Currently we show tcl variable values using hover. We definitely want to keep that, as hover is widely supported across IDEs. However, for those that support code lens, it might be nice to just directly show the Tcl variable values in the document.

**Comment by adeschamps** [comment]
I don't think code lenses are the right UI for this. I've seen some editors (IntelliJ, I think) insert information in the middfle of a line, but it seems like code lenses are expected to have their own line. I'm not sure what nomenclature IntelliJ uses to describe their feature, so I'm not sure if it's analogous to code lenses.

**Comment by adeschamps** [comment]
Since code lenses aren't the right UI element for this in general, I'm going to close this. If someone determines that a particular editor displays code lenses in a way that would make sense for this use case, then we can add this as a configurable feature and enable it for those editors.
