### ISSUE TITLE
Handle boundaries for names with dashes properly

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#77]
In vscode (haven't tried elsewhere), if you ctrl-hover over a proc name or tcl var (like you're about to click to go to definition), it underlines the thing you're about to jump to. But if the name contains dashes, the underlining stops at the dashes -- whatever is doing that doesn't seem to understand where the bounds of the names are. The actual goto definition works fine, this is just a minor aesthetic thing. (Related: double-clicking to select a name doesn't select past dashes. This is more annoying as it affects how people edit the code. But it was also true in the old eclipse version.)

It may be that this is an IDE-specific thing that LSP can't control.

**Comment by adeschamps** [comment]
I'd really like to fix this, because it also causes autocompletions to insert themselves incorrectly if you started out with a partially completed name. 

This is how you can end up with things like `ngs-b` -> `ngs-ngs-bind`

**Comment by adeschamps** [comment]
I believe it's up to the plugin that's providing the language mode to define what a word boundary is. For VSCode, that would be @sirnuke's plugin.

a41f677 fixed the issue with inserting autocompletions, so you no longer get things like `ngs-b` -> `ngs-ngs-bind`.

**Comment by sirnuke** [comment]
^is correct, there's a regex section defining word pattern for VSCode language support.  My extension doesn't implement one, so I assume it's falling back to a C-style default.

I put it on my trello board, and it should be a pretty easy fix.
