### ISSUE TITLE
tcl expansions should work for non-active agents

### ISSUE THREAD

**Issue by marinier** [soartech/soar-language-server#78]
It appears that tcl expansions don't work in files only sourced by non-active agents. Here's my proposed behavior:

* If a file is only sourced by one agent, show the tcl expansions for that agent. It doesn't matter if the agent is the active agent or not.
* If a file is sourced by multiple agents and one of those is the active agent, show the active agent's expansions.
* If a file is sourced by multiple agents and none of them is the active agent, show the expansions for whichever agent comes first in the entry points list in `soarAgents.json`.

Given that which expansion is being shown might not be obvious to the user, it would also be nice if that was displayed somehow. Maybe the simplest would be to inject a comment at the top of the expansion file.

Finally, I'm sure someone will want to be able to change which expansion is shown on the fly -- maybe a code action? But maybe this is a bridge too far for version 1, and we should wait for people to actually request it.

**Comment by adeschamps** [comment]
Fixed in #83
